server:
  port: [LOCAL_PORT]
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  data:
    mongodb:
      uri: [YOUR_MONGO_URI]
      database: rdv_manager_db
  profiles:
    active: debug
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    name: RdvManagerApi
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.grey.sytsas: DEBUG